export const playersInfo =[
  {
    "id": 1,
    "name": "Babar Azam",
    "age": 30,
    "role": "Batsman",
    "bowlingType": "Right-arm off break",
    "battingType": "Right-handed",
    "totalScore": 12902,
    "highestScore": 158,
    "totalWickets": 2,
    "highestWickets": 1,
    "strikeRate": 89.2,
    "teamRole": "Captain",
    "totalCatches": 156
  },
  {
    "id": 2,
    "name": "Shaheen Afridi",
    "age": 25,
    "role": "Bowler",
    "bowlingType": "Left-arm fast",
    "battingType": "Left-handed",
    "totalScore": 1050,
    "highestScore": 52,
    "totalWickets": 280,
    "highestWickets": 6,
    "strikeRate": 115.4,
    "teamRole": "Player",
    "totalCatches": 48
  },
  {
    "id": 3,
    "name": "Mohammad Rizwan",
    "age": 33,
    "role": "Wicketkeeper-Batsman",
    "bowlingType": "Right-arm medium",
    "battingType": "Right-handed",
    "totalScore": 8900,
    "highestScore": 115,
    "totalWickets": 0,
    "highestWickets": 0,
    "strikeRate": 130.2,
    "teamRole": "Player",
    "totalCatches": 175
  },
  {
    "id": 4,
    "name": "Shadab Khan",
    "age": 27,
    "role": "All-rounder",
    "bowlingType": "Right-arm legbreak",
    "battingType": "Right-handed",
    "totalScore": 3200,
    "highestScore": 86,
    "totalWickets": 190,
    "highestWickets": 4,
    "strikeRate": 125.5,
    "teamRole": "Player",
    "totalCatches": 92
  },
  {
    "id": 5,
    "name": "Fakhar Zaman",
    "age": 35,
    "role": "Batsman",
    "bowlingType": "Slow left-arm orthodox",
    "battingType": "Left-handed",
    "totalScore": 9700,
    "highestScore": 210,
    "totalWickets": 3,
    "highestWickets": 2,
    "strikeRate": 94.8,
    "teamRole": "Player",
    "totalCatches": 88
  },
  {
    "id": 6,
    "name": "Haris Rauf",
    "age": 31,
    "role": "Bowler",
    "bowlingType": "Right-arm fast",
    "battingType": "Right-handed",
    "totalScore": 410,
    "highestScore": 34,
    "totalWickets": 210,
    "highestWickets": 5,
    "strikeRate": 110.5,
    "teamRole": "Player",
    "totalCatches": 36
  },
  {
    "id": 7,
    "name": "Imad Wasim",
    "age": 36,
    "role": "All-rounder",
    "bowlingType": "Slow left-arm orthodox",
    "battingType": "Left-handed",
    "totalScore": 4800,
    "highestScore": 92,
    "totalWickets": 160,
    "highestWickets": 5,
    "strikeRate": 128.7,
    "teamRole": "Player",
    "totalCatches": 74
  },
  {
    "id": 8,
    "name": "Naseem Shah",
    "age": 22,
    "role": "Bowler",
    "bowlingType": "Right-arm fast",
    "battingType": "Right-handed",
    "totalScore": 620,
    "highestScore": 33,
    "totalWickets": 150,
    "highestWickets": 5,
    "strikeRate": 90.3,
    "teamRole": "Player",
    "totalCatches": 29
  },
  {
    "id": 9,
    "name": "Iftikhar Ahmed",
    "age": 35,
    "role": "All-rounder",
    "bowlingType": "Right-arm off break",
    "battingType": "Right-handed",
    "totalScore": 5200,
    "highestScore": 94,
    "totalWickets": 45,
    "highestWickets": 3,
    "strikeRate": 126.9,
    "teamRole": "Player",
    "totalCatches": 66
  },
  {
    "id": 10,
    "name": "Saim Ayub",
    "age": 23,
    "role": "Batsman",
    "bowlingType": "Right-arm medium",
    "battingType": "Left-handed",
    "totalScore": 2100,
    "highestScore": 102,
    "totalWickets": 2,
    "highestWickets": 1,
    "strikeRate": 136.8,
    "teamRole": "Player",
    "totalCatches": 22
  },
  {
    "id": 11,
    "name": "Azam Khan",
    "age": 27,
    "role": "Wicketkeeper-Batsman",
    "bowlingType": "Right-arm medium",
    "battingType": "Right-handed",
    "totalScore": 3300,
    "highestScore": 109,
    "totalWickets": 0,
    "highestWickets": 0,
    "strikeRate": 140.3,
    "teamRole": "Player",
    "totalCatches": 56
  },
  {
    "id": 12,
    "name": "Hasan Ali",
    "age": 31,
    "role": "Bowler",
    "bowlingType": "Right-arm fast medium",
    "battingType": "Right-handed",
    "totalScore": 1700,
    "highestScore": 58,
    "totalWickets": 230,
    "highestWickets": 6,
    "strikeRate": 102.5,
    "teamRole": "Player",
    "totalCatches": 59
  },
  {
    "id": 13,
    "name": "Mohammad Nawaz",
    "age": 31,
    "role": "All-rounder",
    "bowlingType": "Slow left-arm orthodox",
    "battingType": "Left-handed",
    "totalScore": 3600,
    "highestScore": 75,
    "totalWickets": 175,
    "highestWickets": 4,
    "strikeRate": 121.3,
    "teamRole": "Player",
    "totalCatches": 70
  },
  {
    "id": 14,
    "name": "Abrar Ahmed",
    "age": 27,
    "role": "Bowler",
    "bowlingType": "Right-arm legbreak",
    "battingType": "Right-handed",
    "totalScore": 350,
    "highestScore": 25,
    "totalWickets": 85,
    "highestWickets": 7,
    "strikeRate": 95.6,
    "teamRole": "Player",
    "totalCatches": 18
  },
  {
    "id": 15,
    "name": "Usama Mir",
    "age": 29,
    "role": "Bowler",
    "bowlingType": "Right-arm legbreak",
    "battingType": "Right-handed",
    "totalScore": 890,
    "highestScore": 37,
    "totalWickets": 110,
    "highestWickets": 4,
    "strikeRate": 98.4,
    "teamRole": "Player",
    "totalCatches": 26
  },
  {
    "id": 16,
    "name": "Abdullah Shafique",
    "age": 25,
    "role": "Batsman",
    "bowlingType": "Right-arm off break",
    "battingType": "Right-handed",
    "totalScore": 4100,
    "highestScore": 201,
    "totalWickets": 0,
    "highestWickets": 0,
    "strikeRate": 93.7,
    "teamRole": "Player",
    "totalCatches": 41
  },
  {
    "id": 17,
    "name": "Saud Shakeel",
    "age": 29,
    "role": "Batsman",
    "bowlingType": "Left-arm orthodox",
    "battingType": "Left-handed",
    "totalScore": 3800,
    "highestScore": 208,
    "totalWickets": 1,
    "highestWickets": 1,
    "strikeRate": 88.9,
    "teamRole": "Player",
    "totalCatches": 37
  },
  {
    "id": 18,
    "name": "Salman Ali Agha",
    "age": 31,
    "role": "All-rounder",
    "bowlingType": "Right-arm off break",
    "battingType": "Right-handed",
    "totalScore": 3300,
    "highestScore": 125,
    "totalWickets": 65,
    "highestWickets": 4,
    "strikeRate": 118.2,
    "teamRole": "Player",
    "totalCatches": 44
  }
]



